export const IndiaStates = [
 // States
 { name:"Andhra Pradesh", type:"State" },
 { name:"Arunachal Pradesh", type:"State" },
 { name:"Assam", type:"State" },
 { name:"Bihar", type:"State" },
 { name:"Chhattisgarh", type:"State" },
 { name:"Goa", type:"State" },
 { name:"Gujarat", type:"State" },
 { name:"Haryana", type:"State" },
 { name:"Himachal Pradesh", type:"State" },
 { name:"Jharkhand", type:"State" },
 { name:"Karnataka", type:"State" },
 { name:"Kerala", type:"State" },
 { name:"Madhya Pradesh", type:"State" },
 { name:"Maharashtra", type:"State" },
 { name:"Manipur", type:"State" },
 { name:"Meghalaya", type:"State" },
 { name:"Mizoram", type:"State" },
 { name:"Nagaland", type:"State" },
 { name:"Odisha", type:"State" },
 { name:"Punjab", type:"State" },
 { name:"Rajasthan", type:"State" },
 { name:"Sikkim", type:"State" },
 { name:"Tamil Nadu", type:"State" },
 { name:"Telangana", type:"State" },
 { name:"Tripura", type:"State" },
 { name:"Uttar Pradesh", type:"State" },
 { name:"Uttarakhand", type:"State" },
 { name:"West Bengal", type:"State" },
 // Union Territories
 { name:"Andaman and Nicobar Islands", type:"UT" },
 { name:"Chandigarh", type:"UT" },
 { name:"Dadra and Nagar Haveli and Daman & Diu", type:"UT" },
 { name:"Delhi", type:"UT" },
 { name:"Jammu and Kashmir", type:"UT" },
 { name:"Ladakh", type:"UT" },
 { name:"Lakshadweep", type:"UT" },
 { name:"Puducherry", type:"UT" }
];

